# .github/workflows/deploy-production.yaml
on:
  release:
    types: [published]

jobs:
  release-production:
    name: 🕋  Release to Production
    if: startsWith(github.ref_name, 'v') # the prefix we have added to the tag
    environment: production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # - name: 📥 Get Artifact from Release
      #   uses: dsaltares/fetch-gh-release-asset@master
      #   with:
      #     version: ${{ github.event.release.id }}
      #     file: cdk.out.zip
    
      - name: 📥 Get Artifact from Release
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "tfplan.zip"
          extract: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-central-1
          
      - name: Deploy Artifact
        run: |
          ls -R
          # terraform apply "tf_plan"
          echo "Deploy to Production successfull 🎉"
