# .github/workflows/deploy-production.yaml
on:
  workflow_call:

jobs:
  release-production:
    name: 🕋 Release to Production
    # if: startsWith(github.ref_name, 'v') && github.event_name == 'workflow_call' # the prefix we have added to the tag
    environment: production
    runs-on: ubuntu-latest
    # permissions:
    #   id-token: write
    #   contents: write
    steps:
      # - name: 📥 Get Artifact from Release
      #   uses: dsaltares/fetch-gh-release-asset@master
      #   with:
      #     version: ${{ github.event.release.id }}
      #     file: cdk.out.zip

      - name: 📥 Get Artifact from Release
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          # tag: "v1.0.0"
          fileName: "tripevibe-artifacts.zip"
          extract: true

      # - name: 🦢 Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
      #     aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Deploy Artifact
        run: |
          ls -R
          # terraform apply "tf_plan"
          echo "Deploy to Production successfull 🎉"
